#!/usr/bin/env python3
"""
Script to extract Firebase configuration values from google-services.json and GoogleService-Info.plist
and generate the firebase_options.dart file.

Usage:
1. Place your google-services.json file in the android/app/ directory
2. Place your GoogleService-Info.plist file in the ios/Runner/ directory (optional)
3. Run: python3 extract_firebase_config.py
"""

import json
import os
import plistlib

def extract_config():
    # Path to google-services.json
    android_json_path = "android/app/google-services.json"
    ios_plist_path = "ios/Runner/GoogleService-Info.plist"
    
    if not os.path.exists(android_json_path):
        print("❌ google-services.json not found!")
        print("Please place your google-services.json file in android/app/ directory")
        return
    
    try:
        # Extract Android configuration
        with open(android_json_path, 'r') as f:
            android_config = json.load(f)
        
        # Extract Android values
        project_id = android_config['project_info']['project_id']
        storage_bucket = android_config['project_info']['storage_bucket']
        sender_id = android_config['project_info']['project_number']
        
        # Get the first client (your app)
        android_client = android_config['client'][0]
        android_app_id = android_client['client_info']['mobilesdk_app_id']
        android_api_key = android_client['api_key'][0]['current_key']
        
        print("✅ Successfully extracted Android Firebase configuration!")
        print("\n📋 Android Configuration Values:")
        print(f"Project ID: {project_id}")
        print(f"App ID: {android_app_id}")
        print(f"API Key: {android_api_key}")
        print(f"Sender ID: {sender_id}")
        print(f"Storage Bucket: {storage_bucket}")
        
        # Try to extract iOS configuration
        ios_app_id = android_app_id  # Default to Android values
        ios_api_key = android_api_key
        reversed_client_id = "com.googleusercontent.apps.YOUR_CLIENT_ID"
        
        if os.path.exists(ios_plist_path):
            try:
                with open(ios_plist_path, 'rb') as f:
                    ios_config = plistlib.load(f)
                
                ios_app_id = ios_config.get('GOOGLE_APP_ID', android_app_id)
                ios_api_key = ios_config.get('API_KEY', android_api_key)
                reversed_client_id = ios_config.get('REVERSED_CLIENT_ID', reversed_client_id)
                
                print("\n✅ Successfully extracted iOS Firebase configuration!")
                print("\n📋 iOS Configuration Values:")
                print(f"iOS App ID: {ios_app_id}")
                print(f"iOS API Key: {ios_api_key}")
                print(f"Reversed Client ID: {reversed_client_id}")
                
                # Update Info.plist with reversed client ID
                update_info_plist(reversed_client_id)
                
            except Exception as e:
                print(f"\n⚠️  Could not read iOS configuration: {e}")
                print("Using Android values for iOS (this should work for basic functionality)")
        else:
            print(f"\n⚠️  iOS GoogleService-Info.plist not found at {ios_plist_path}")
            print("Using Android values for iOS (this should work for basic functionality)")
        
        # Generate firebase_options.dart content
        dart_content = f'''// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    if (kIsWeb) {{
      return web;
    }}
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }}
  }}

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '{android_api_key}',
    appId: '{android_app_id}',
    messagingSenderId: '{sender_id}',
    projectId: '{project_id}',
    authDomain: '{project_id}.firebaseapp.com',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{android_api_key}',
    appId: '{android_app_id}',
    messagingSenderId: '{sender_id}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '{ios_api_key}',
    appId: '{ios_app_id}',
    messagingSenderId: '{sender_id}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '{ios_api_key}',
    appId: '{ios_app_id}',
    messagingSenderId: '{sender_id}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '{android_api_key}',
    appId: '{android_app_id}',
    messagingSenderId: '{sender_id}',
    projectId: '{project_id}',
    authDomain: '{project_id}.firebaseapp.com',
    storageBucket: '{storage_bucket}',
  );
}}'''
        
        # Write to firebase_options.dart
        with open('lib/firebase_options.dart', 'w') as f:
            f.write(dart_content)
        
        print("\n✅ Updated lib/firebase_options.dart with your configuration!")
        print("\n🚀 Next steps:")
        print("1. Run: flutter clean && flutter pub get")
        print("2. Run: flutter run")
        print("3. Test authentication with your phone number and Google account")
        
    except Exception as e:
        print(f"❌ Error reading google-services.json: {e}")
        print("Please make sure the file is valid JSON and properly formatted.")

def update_info_plist(reversed_client_id):
    """Update iOS Info.plist with the correct REVERSED_CLIENT_ID"""
    info_plist_path = "ios/Runner/Info.plist"
    
    try:
        with open(info_plist_path, 'r') as f:
            content = f.read()
        
        # Replace the placeholder with actual value
        updated_content = content.replace('REVERSED_CLIENT_ID_VALUE', reversed_client_id)
        
        with open(info_plist_path, 'w') as f:
            f.write(updated_content)
        
        print(f"✅ Updated iOS Info.plist with REVERSED_CLIENT_ID: {reversed_client_id}")
        
    except Exception as e:
        print(f"⚠️  Could not update Info.plist: {e}")
        print(f"Please manually replace 'REVERSED_CLIENT_ID_VALUE' with '{reversed_client_id}' in ios/Runner/Info.plist")

if __name__ == "__main__":
    extract_config()