// Mock generated by Mockito
import 'package:attendance_tracker/services/database_service.dart';
import 'package:attendance_tracker/services/database_helper.dart';
import 'package:mockito/mockito.dart';

class MockDatabaseService extends Mock implements DatabaseService {}
class MockDatabaseHelper extends Mock implements DatabaseHelper {}