// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChQQmktqsiSNPibSq9h-l0Y-VwsnrtNdM',
    appId: '1:377349051863:android:e10543e989ceb1a9916792',
    messagingSenderId: '377349051863',
    projectId: 'ttendance-tracker-app',
    authDomain: 'ttendance-tracker-app.firebaseapp.com',
    storageBucket: 'ttendance-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQQmktqsiSNPibSq9h-l0Y-VwsnrtNdM',
    appId: '1:377349051863:android:e10543e989ceb1a9916792',
    messagingSenderId: '377349051863',
    projectId: 'ttendance-tracker-app',
    storageBucket: 'ttendance-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxz8trIfGJhEKxkog6upBK4dS8Ql2pac',
    appId: '1:377349051863:ios:7ca0ec68eb389677916792',
    messagingSenderId: '377349051863',
    projectId: 'ttendance-tracker-app',
    storageBucket: 'ttendance-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyxz8trIfGJhEKxkog6upBK4dS8Ql2pac',
    appId: '1:377349051863:ios:7ca0ec68eb389677916792',
    messagingSenderId: '377349051863',
    projectId: 'ttendance-tracker-app',
    storageBucket: 'ttendance-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChQQmktqsiSNPibSq9h-l0Y-VwsnrtNdM',
    appId: '1:377349051863:android:e10543e989ceb1a9916792',
    messagingSenderId: '377349051863',
    projectId: 'ttendance-tracker-app',
    authDomain: 'ttendance-tracker-app.firebaseapp.com',
    storageBucket: 'ttendance-tracker-app.firebasestorage.app',
  );
}